export const GET_ALL_ADMIN_USERS = 'get_all_admin_users'
export const GET_ALL_SECTIONS = 'get_all_sections'
export const GET_SECTION_DETAILS = 'get_section_details'
export const GET_ALL_COLLECTIONS = 'get_all_collections'
export const GET_COLLECTION_DETAILS = 'get_collection_details'
export const GET_ALL_TOP_BANNERS = 'get_all_top_banners'